#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Conference
#        - App\Entity\Comment
##        - App\Entity\User

easy_admin:
    site_name: Liste des conférences

    design:
        menu:
            - { route: "homepage", label: "Back to the website", icon: "home" }
            - { entity: "Conference", label: "Conferences", icon: "map-marker" }
            - { entity: "Comment", label: "Comments", icon: "comments" }
    entities:
        Conference:
            class: App\Entity\Conference
            list:
                fields:
                    - { property: "year", type: "string" }
                    - { property: "city", type: "string" }
                    - { property: "isInternational", type: "boolean" }

            edit:
                fields:
                    - { property: "city" }
                    - { property: "year" }
                    - { property: "isInternational" }
                    - { property: "comments" }

                    

        Comment:
            class: App\Entity\Comment
            list:
                fields:
                    - author
                    - { property: "email", type: "email" }
                    - { property: "createdAt", type: "datetime" }
                    - { property: "conference" }

                sort: ["createdAt", "ASC"]
                filters: ["conference"]
            edit:
                fields:
                    - { property: "conference" }
                    - {
                          property: "createdAt",
                          type: datetime,
                          type_options: { attr: { readonly: true } },
                      }
                    - { property: "note" }
                    - "author"
                    - { property: "email", type: "email" }
                    - text
